name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - redesign
    paths:
      - "root/portfolio/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Dependencies
        run: |
          cd root/portfolio
          npm ci
      - name: Build
        run: |
          cd root/portfolio
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./root/portfolio/build
          destination_dir: portfolio
